name: 'deploy-mate-develop-service'
description: 'Creates action files for Go code by AgelCyber'
inputs:
  project:
    description: 'Project ID'
    required: true
  location:
    description: 'Deploy Location ID'
    required: true
  name:
    description: 'Deployment Name'
    required: true
  image:
    description: 'Docker Image to deploy'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2

    - name: 'Set up Docker'
      uses: docker/setup-action@v2

    - name: 'Build and push Docker image'
      shell: bash
      run: |
        echo "LOCATION=${{ inputs.location }}" >> $GITHUB_ENV
        echo "PROJECT=${{ inputs.project }}" >> $GITHUB_ENV
        echo "NAME=${{ inputs.name }}" >> $GITHUB_ENV
        echo "IMAGE=${{ inputs.image }}" >> $GITHUB_ENV
        docker build -t $IMAGE -f Dockerfile .
        docker push $IMAGE

    - name: 'Run deployment script'
      shell: bash
      run: |
        docker run -e LOCATION=$LOCATION -e PROJECT=$PROJECT -e NAME=$NAME -e IMAGE=$IMAGE $IMAGE

branding:
  icon: 'cloud'
  color: 'red'
