name: "deploy-mate-develop-service"
description: "Creates action files for Go code by AgelCyber"
inputs:
  project:
    description: "Project ID"
    required: true
  location:
    description: "Deploy Location ID"
    required: true
  name:
    description: "Deployment Name"
    required: true
  to:
    description: "Deployment to Name"
    required: true
  image:
    description: "Docker Image to deploy"
    required: true
  type:
    description: "Action Type"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
