root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/deploy_mate/main"
  cmd = "go build -o ./tmp/deploy_mate/main ./app/deploy_mate"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  log = "build-errors.log"
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false


