name: Deploy Production
on:
  push:
    branches:
      - main
jobs:
  build-docker-image:
    runs-on: self-hosted
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: asia-southeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Pre Build
        run: "docker system prune -af && docker system prune --volumes -af"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: app/scb_enet/Dockerfile
          push: true
          tags: asia-southeast1-docker.pkg.dev/scamo-group/scamonode/scb-easynet-service:latest
    outputs:
      image: asia-southeast1-docker.pkg.dev/scamo-group/scamonode/scb-easynet-service@${{ steps.docker_build.outputs.digest }}

  deploy-production-1:
    needs: build-docker-image
    runs-on: self-hosted
    steps:
      - uses: deploys-app/deploys-action@v1
        with:
          project: toberich-staging
          location: gke.cluster-rcf2
          name: deploy-mate-develop-service
          image: ${{ needs.build-docker-image.outputs.image }}
        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
